/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import controlador.Metodos;

/**
 *
 * @author angel
 */
public class Vista1 extends javax.swing.JFrame {

	/**
	 * Creates new form Vista1
	 */
	private final Metodos metodos;

	public Vista1() {
		initComponents();
		this.setLocationRelativeTo(null);
		metodos = new Metodos();
		panelResultado.setVisible(false);
		btnCrearUsuario.setVisible(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		txtRuta = new javax.swing.JTextField();
		lblMensaje = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		lblTiempo = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tbListarVotos = new javax.swing.JTable();
		panelResultado = new javax.swing.JPanel();
		lblItem = new javax.swing.JLabel();
		lblVoto = new javax.swing.JLabel();
		lblItems = new javax.swing.JLabel();
		lblVotos = new javax.swing.JLabel();
		lblItem2 = new javax.swing.JLabel();
		lblNumBotos = new javax.swing.JLabel();
		btnContar = new javax.swing.JButton();
		btnCrearUsuario = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SeleccionarArchivo",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

		txtRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblMensaje.setText("CARGAR DATOS");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel2.setText("Ruta:");

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jButton1.setText("Abrir");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 455,
												Short.MAX_VALUE)
										.addComponent(txtRuta))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(28, 28, 28)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1)
								.addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE,
										31, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(9, 9, 9).addComponent(lblTiempo,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
						.addContainerGap()));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 720, -1));

		tbListarVotos.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jScrollPane1.setViewportView(tbListarVotos);

		getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 167, 764, 279));

		panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 204))); // NOI18N
		panelResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lblItem.setText("Item:");
		panelResultado.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

		lblVoto.setText("Voto:");
		panelResultado.add(lblVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
		panelResultado.add(lblItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 510, 30));
		panelResultado.add(lblVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 510, 30));

		lblItem2.setText("Total Votos:");
		panelResultado.add(lblItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
		panelResultado.add(lblNumBotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 370, 30));

		btnContar.setText("Contar Votos");
		btnContar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnContarActionPerformed(evt);
			}
		});
		panelResultado.add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, 30));

		getContentPane().add(panelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 630, 160));

		btnCrearUsuario.setText("CREAR USUARIO");
		btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCrearUsuarioActionPerformed(evt);
			}
		});
		getContentPane().add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			String ruta = metodos.getRuta();
			String separador = JOptionPane.showInputDialog("Espesifique el separador:  ");
			if (metodos.verificarExtension(ruta)) {
				if (separador.equals("::") || separador.equals(":") || separador.equals(";") || separador.equals(".")
						|| separador.equals(",")) {
					txtRuta.setText(ruta);
					lblMensaje.setText("Lectura Exitosa");
					if (metodos.tamanioArchivo(new File(ruta)) < 4) {
						tbListarVotos.setModel(metodos.listaVotos(ruta, separador, lblTiempo));
						btnCrearUsuario.setVisible(true);
					} else {
						metodos.listaVotos(ruta, separador, lblTiempo);
					}

				} else {
					JOptionPane.showMessageDialog(null, "Separador Incorrecto" + separador);
				}
			} else {
				lblMensaje.setText("Error el archivo debe tener la extension .txt .csv .dat");
			}
		} catch (Exception e) {
			System.out.println();
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnContarActionPerformed
		try {
			int item = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Item"));
			int total = metodos.contarVotos(tbListarVotos, item);
			lblNumBotos.setText("El item " + item + " tiene " + total + " votos");
		} catch (Exception e) {
		}
	}// GEN-LAST:event_btnContarActionPerformed

	private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearUsuarioActionPerformed
		try {
			int usuario = Integer.parseInt(JOptionPane.showInputDialog("Digite el numero de usuario"));
			ArrayList<Integer> votos = metodos.mostrarVotosUsuario(tbListarVotos, usuario);
			ArrayList<Integer> items = metodos.mostrarItemsUsuario(tbListarVotos, usuario);
			if (usuario > 0) {
				panelResultado.setVisible(true);
				lblItems.setText(items.toString());
				lblVotos.setText(votos.toString());
			} else {
				JOptionPane.showMessageDialog(this, "Ingrese un Usuario");
			}

		} catch (Exception e) {
		}
	}// GEN-LAST:event_btnCrearUsuarioActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Vista1().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnContar;
	private javax.swing.JButton btnCrearUsuario;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblItem;
	private javax.swing.JLabel lblItem2;
	private javax.swing.JLabel lblItems;
	private javax.swing.JLabel lblMensaje;
	private javax.swing.JLabel lblNumBotos;
	private javax.swing.JLabel lblTiempo;
	private javax.swing.JLabel lblVoto;
	private javax.swing.JLabel lblVotos;
	private javax.swing.JPanel panelResultado;
	private javax.swing.JTable tbListarVotos;
	private javax.swing.JTextField txtRuta;
	// End of variables declaration//GEN-END:variables
}
